---
title: "Seismophobia EDA"
author: "Group 11 - Junghoo Kim, Dustin Burnham, Dustin Andrews, Trevor Kinsey"
date: "11/21/2020"
output:
  md_document: default
  pdf_document: default
  html_document: default
---

## Outline

This document will provide a first pass at an EDA of the `fivethirtyeight` San Andreas Earthquake data set.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, message = FALSE}
library(tidyverse)
library(here)
library(ggthemes)
```

```{r raw data, message = FALSE}
earthquake <- read_csv(here('data', 'raw', 'earthquake_data.csv'))

# Before we go further, split into 30% test, 70% train
set.seed(42)
train_ratio = 0.7
train_index <- sample(1:nrow(earthquake), train_ratio * nrow(earthquake))

```

```{r minor data wrangling before EDA, message = FALSE}
earthquake_fct <- earthquake %>%
  filter(row_number() %in% train_index) %>%
  rename(
    worry_earthquake = "In general, how worried are you about earthquakes?",
    worry_big_one = "How worried are you about the Big One, a massive, catastrophic earthquake?",
    think_lifetime_big_one = 'Do you think the "Big One" will occur in your lifetime?',
    experience_earthquake = "Have you ever experienced an earthquake?",
    prepared_earthquake = "Have you or anyone in your household taken any precautions for an earthquake (packed an earthquake survival kit, prepared an evacuation plan, etc.)?",
    familliar_san_andreas = "How familiar are you with the San Andreas Fault line?",
    familiar_yellowstone = "How familiar are you with the Yellowstone Supervolcano?",
    age = "Age",
    gender = "What is your gender?",
    household_income = "How much total combined money did all members of your HOUSEHOLD earn last year?",
    us_region = "US Region"
  ) %>%
  mutate_all(na_if, "") %>%
  mutate_if(is.character, as.factor) %>%
  select(-worry_big_one) %>%
  mutate(worry_earthquake = fct_relevel(worry_earthquake, c("Extremely worried", "Very worried", "Somewhat worried", "Not so worried", "Not at all worried")))

earthquake_fct %>%  
  head(10) %>% 
  knitr::kable(caption = "Head of Earthquake Data Set - Train Split ")
```
```{r}
earthquake_fct %>%  
  tail(10) %>% 
  knitr::kable(caption = "Tail of Earthquake Data Set")
```


```{r - prediction target}
earthquake_fct$worry_earthquake %>%
  levels()
```

```{r - Summary Tables of Target Count}
earthquake_fct %>% 
  group_by(worry_earthquake) %>% 
  summarize(count = n()) %>% 
  knitr::kable(caption="Count of Different Target Levels in Training Set")
```
```{r - Summary Tables}
earthquake_fct %>%
  is.na() %>%
  colSums() %>%
  knitr::kable(col.names = "Count of NA's in Feature", caption="NA Count by Feature In Training Set")
```



```{r - Class Distribution}
earthquake_fct %>% 
  ggplot() +
    aes(x = worry_earthquake ,
        color = worry_earthquake,
        fill = worry_earthquake) +
  geom_histogram(stat = "count") +
  scale_fill_tableau() +
  scale_colour_tableau() +
  labs(x = "Worry Response",
       y = "Count",
       title = "Earthquake Worry Response Distribution",
       subtitle="Training Set") +
  theme(legend.title = element_blank(),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```


```{r - 2D Histograms, fig.height=10, fig.width=10}
earthquake_fct %>% 
  pivot_longer(!worry_earthquake, names_to = "feature", values_to = "value") %>% 
  add_count(worry_earthquake, feature, value) %>% 
  ggplot() +
    aes(x = value, 
        y = worry_earthquake, 
        fill = n) +
  geom_tile(na.rm = TRUE) +
  xlab("Feature") + 
  ylab("How worried are you about an earthquake?") + 
  facet_wrap(. ~ feature, scale = "free", ncol = 3) +
  scale_fill_viridis_c(direction=-1) +
  theme_bw() +
  theme(strip.text = element_text(size=10),
        axis.text = element_text(size = 8),
        axis.text.x = element_text(angle = 90))
```

